"""empty message

Revision ID: 61b13a660e21
Revises: 
Create Date: 2024-07-27 17:41:40.397201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b13a660e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('summary_id')

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('summary_id')

    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('summary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'summary', ['summary_id'], ['id'])
        batch_op.drop_column('summary')

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'summary', ['summary_id'], ['id'])
        batch_op.drop_column('summary')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'summary', ['summary_id'], ['id'])
        batch_op.drop_column('summary')

    op.create_table('summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=80), nullable=False),
    sa.Column('datetime', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
